name: ActiCorePlus
version: '${project.version}'
main: com.metaxcrew.acticoreplus.ActiCorePlus
api-version: 1.18
authors: [ MatLabs ]
depend: [PlaceholderAPI]

commands:
  gm:
    description: GUI
    aliases: [gmc, gms, gmsp, gma, gmgui, gamemode]
  time:
    description: GUI
    aliases: [ tm, time, day, night, tmgui]
  faq:
    aliases: [ FAQ ]
    description: Frequently asked questions
  fly:
    aliases: [flight,flyon]
    description: Fly