name: ActiCorePlus
version: '${project.version}'
main: com.metaxcrew.acticoreplus.ActiCorePlus
api-version: 1.18
authors: [ MatLabs ]
depend: [PlaceholderAPI]

commands:
  gm:
    description: GUI
    aliases: [gma, gmgui, gamemode]
  time:
    description: GUI
    aliases: [ tm, time, day, night, tmgui]
  faq:
    aliases: [ FAQ ]
    description: Frequently asked questions
  fly:
    aliases: [flight,flyon]
    description: Fly
  gmc:
    aliases: [gm1,gamemode 1]
    description: gmc
  gms:
    aliases: [ gm0,gamemode 0 ]
    description: gms
  gma:
    aliases: [ gm4,gamemode 4 ]
    description: gma
  gmsp:
    aliases: [ gm3,gamemode 3 ]
    description: gmsp